In [1]:
# Import Pandas
import numpy as np
import pandas as pd
import re 

# Read the file in JSON format
df = pd.read_csv('G2 - final_scout_not_dummy.csv')

# Get rid of disturbing warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24129 entries, 0 to 24128
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make_Model               24129 non-null  object
 1   Make                     24129 non-null  object
 2   Model                    24129 non-null  object
 3   Location                 24129 non-null  object
 4   Price                    24129 non-null  float64
 5   Body_Type                24129 non-null  object
 6   Type                     24129 non-null  object
 7   Doors                    24129 non-null  int64
 8   Mileage                  24129 non-null  int64
 9   Gearbox                  24129 non-null  object
 10  Fuel_Type                24129 non-null  object
 11  Colour                   24129 non-null  object
 12  Metallic                 24129 non-null  int64
 13  Dealer                   24129 non-null  int64
 14  Seats                    24129 non-null  int64
 15  Power                    24129 non-null  int64
 16  Engine_Size              24129 non-null  float64
 17  CO2_Emissions            24129 non-null  int64
 18  Four_Wheel_Drive         24129 non-null  int64
 19  Cylinders                24129 non-null  float64
 20  Fuel_Consumption         24129 non-null  float64
 21  Comfort_and_Convenience  24129 non-null  object
 22  Entertainment_and_Media  24129 non-null  object
 23  Safety_and_Security      24129 non-null  object
 24  Extras                   24129 non-null  object
 25  Full_Service_History     24129 non-null  int64
 26  Non_Smoker_Vehicle       24129 non-null  int64
 27  Emission_Class           24129 non-null  float64
 28  Upholstery               24129 non-null  int64
 29  Previous_Owner           24129 non-null  int64
 30  Electric_Car             24129 non-null  int64
 31  Energy_Efficiency_Class  24129 non-null  int64
 32  Taxi_or_Rental_Car       24129 non-null  int64
 33  Warranty_Category        24129 non-null  int64
 34  First_Registration_Year  24129 non-null  int64
 35  Age                      24129 non-null  int64
 36  General_Inspection_Year  24129 non-null  int64
dtypes: float64(5), int64(19), object(13)
memory usage: 6.8+ MB

In [4]:
df.sample(5)

,Make_Model,Make,Model,Location,Price,Body_Type,Type,Doors,Mileage,Gearbox,...,Emission_Class,Upholstery,Previous_Owner,Electric_Car,Energy_Efficiency_Class,Taxi_or_Rental_Car,Warranty_Category,First_Registration_Year,Age,General_Inspection_Year
12784,Skoda Scala,Skoda,Scala,DE,29790.0,Sedan,Pre-registered,5,90,Automatic,...,6.0,0,1,0,6,0,3,2022,0,2025
1511,Opel Corsa,Opel,Corsa,DE,8500.0,Compact,Used,5,28452,Manual,...,5.0,1,2,0,7,0,2,2014,8,2026
14359,Dacia Sandero,Dacia,Sandero,ES,12490.0,Sedan,Used,5,13678,Manual,...,6.0,0,1,0,5,0,2,2017,5,2026
13418,Dacia Duster,Dacia,Duster,DE,18500.0,Off-Road/Pick-up,Used,4,49481,Manual,...,6.0,0,1,0,5,0,2,2019,3,2026
1714,Opel Adam,Opel,Adam,DE,12090.0,Compact,Used,3,49235,Manual,...,6.0,0,2,0,5,0,6,2019,3,2026

In [5]:
df10=pd.get_dummies(df, prefix=['BT'], ['Body_Type'])
df10

,Make_Model,Make,Model,Location,Price,Type,Doors,Mileage,Gearbox,Fuel_Type,...,Warranty_Category,First_Registration_Year,Age,General_Inspection_Year,BT_Compact,BT_Convertible,BT_Coupe,BT_Off-Road/Pick-up,BT_Sedan,BT_Station wagon
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,ES,16950.0,Used,5,120200,Manual,Diesel,...,3,2016,6,2026,1,0,0,0,0,0
1,Mercedes-Benz A 35 AMG,Mercedes-Benz,A 35 AMG,ES,46990.0,Used,5,18995,Automatic,Benzine,...,2,2020,2,2026,1,0,0,0,0,0
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,A 45 AMG,ES,16800.0,Used,5,197000,Automatic,Diesel,...,2,2015,7,2026,1,0,0,0,0,0
3,Mercedes-Benz C 160,Mercedes-Benz,C 160,DE,4690.0,Used,3,165000,Manual,Benzine,...,2,2005,17,2026,1,0,0,0,0,0
4,Mercedes-Benz CLA 180,Mercedes-Benz,CLA 180,ES,22550.0,Used,5,83339,Manual,Diesel,...,2,2018,4,2026,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24124,Volvo S60,Volvo,S60,ES,4999.0,Used,4,166512,Manual,Benzine,...,2,2004,18,2023,0,0,0,0,1,0
24125,Volvo S90,Volvo,S90,ES,37600.0,Used,4,40345,Automatic,Diesel,...,2,2019,3,2026,0,0,0,0,1,0
24126,Volvo S40,Volvo,S40,NL,5499.0,Used,4,145000,Automatic,Benzine,...,2,2004,18,2023,0,0,0,0,1,0
24127,Volvo C30,Volvo,C30,BE,7300.0,Used,3,96000,Manual,Diesel,...,3,2011,11,2023,0,0,0,0,1,0
24128,Volvo S90,Volvo,S90,NL,29900.0,Used,4,94343,Automatic,Benzine,...,2,2017,5,2026,0,0,0,0,1,0

In [7]:
df11=pd.get_dummies(df, prefix=['Type','GB','FT'], columns=['Type','Gearbox','Fuel_Type'])
df11

,Make_Model,Make,Model,Location,Price,Body_Type,Doors,Mileage,Colour,Metallic,...,Type_Used,GB_Automatic,GB_Manual,GB_Semi-automatic,FT_Benzine,FT_Bi-fuel,FT_Diesel,FT_Electric,FT_LPG,FT_Other
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,ES,16950.0,Compact,5,120200,Black,1,...,1,0,1,0,0,0,1,0,0,0
1,Mercedes-Benz A 35 AMG,Mercedes-Benz,A 35 AMG,ES,46990.0,Compact,5,18995,Yellow,0,...,1,1,0,0,1,0,0,0,0,0
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,A 45 AMG,ES,16800.0,Compact,5,197000,White,1,...,1,1,0,0,0,0,1,0,0,0
3,Mercedes-Benz C 160,Mercedes-Benz,C 160,DE,4690.0,Compact,3,165000,Black,1,...,1,0,1,0,1,0,0,0,0,0
4,Mercedes-Benz CLA 180,Mercedes-Benz,CLA 180,ES,22550.0,Compact,5,83339,Silver,0,...,1,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24124,Volvo S60,Volvo,S60,ES,4999.0,Sedan,4,166512,Black,0,...,1,0,1,0,1,0,0,0,0,0
24125,Volvo S90,Volvo,S90,ES,37600.0,Sedan,4,40345,Black,0,...,1,1,0,0,0,0,1,0,0,0
24126,Volvo S40,Volvo,S40,NL,5499.0,Sedan,4,145000,Grey,0,...,1,1,0,0,1,0,0,0,0,0
24127,Volvo C30,Volvo,C30,BE,7300.0,Sedan,3,96000,Grey,1,...,1,0,1,0,0,0,1,0,0,0
24128,Volvo S90,Volvo,S90,NL,29900.0,Sedan,4,94343,Blue,1,...,1,1,0,0,1,0,0,0,0,0

In [8]:
df11.T

,0,1,2,3,4,5,6,7,8,9,...,24119,24120,24121,24122,24123,24124,24125,24126,24127,24128
Make_Model,Mercedes-Benz A 160,Mercedes-Benz A 35 AMG,Mercedes-Benz A 45 AMG,Mercedes-Benz C 160,Mercedes-Benz CLA 180,Mercedes-Benz A 220,Mercedes-Benz A 35 AMG,Mercedes-Benz A 200,Mercedes-Benz A 160,Mercedes-Benz A 45 AMG,...,Volvo S60,Volvo S90,Volvo S90,Volvo S90,Volvo V40,Volvo S60,Volvo S90,Volvo S40,Volvo C30,Volvo S90
Make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,...,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo
Model,A 160,A 35 AMG,A 45 AMG,C 160,CLA 180,A 220,A 35 AMG,A 200,A 160,A 45 AMG,...,S60,S90,S90,S90,V40,S60,S90,S40,C30,S90
Location,ES,ES,ES,DE,ES,ES,BE,ES,BE,ES,...,BE,NL,ES,ES,BE,ES,ES,NL,BE,NL
Price,16950.0,46990.0,16800.0,4690.0,22550.0,26900.0,44999.0,23900.0,14200.0,37999.0,...,33500.0,38000.0,27190.0,27190.0,13000.0,4999.0,37600.0,5499.0,7300.0,29900.0
Body_Type,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,...,Sedan,Sedan,Sedan,Sedan,Sedan,Sedan,Sedan,Sedan,Sedan,Sedan
Doors,5,5,5,3,5,5,5,5,5,5,...,4,4,4,4,5,4,4,4,3,4
Mileage,120200,18995,197000,165000,83339,48900,56876,21854,99016,90000,...,53000,44873,93757,93757,114000,166512,40345,145000,96000,94343
Colour,Black,Yellow,White,Black,Silver,Grey,Grey,White,Grey,Black,...,Red,Black,Black,Black,Grey,Black,Black,Grey,Grey,Blue
Metallic,1,0,1,1,0,1,0,0,1,1,...,1,1,0,0,1,0,0,0,1,1
Dealer,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,0,1,1,1,1,1
Seats,5,5,5,4,5,5,5,5,5,5,...,5,5,5,5,5,5,4,5,4,5
Power,75,225,100,90,90,140,225,102,66,280,...,228,228,140,140,88,154,288,125,84,187
Engine_Size,1595.0,1991.0,2143.0,1799.0,1595.0,1991.0,1991.0,1991.0,1461.0,1991.0,...,1969.0,1969.0,1969.0,1969.0,1969.0,2521.0,1969.0,2435.0,1560.0,1969.0
CO2_Emissions,126,169,162,196,144,141,168,123,98,162,...,168,149,149,149,94,145,149,217,99,149
Four_Wheel_Drive,0,1,1,0,0,0,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
Cylinders,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,5.0,4.0,5.0,4.0,4.0
Fuel_Consumption,5.4,7.3,4.9,8.2,6.3,6.1,0.0,5.4,3.8,6.9,...,7.4,7.6,4.4,4.4,3.6,9.1,2.0,9.1,3.8,6.5
Comfort_and_Convenience,Standard,Standard,Business,Business,Standard,Standard,Business,Business,Business,Standard,...,Premium,Premium,Business,Business,Business,Business,Business,Business,Business,Premium
Entertainment_and_Media,Standard,Standard,Standard,Standard,Standard,Standard,Standard,Standard,Business,Standard,...,Business,Premium,Standard,Standard,Business,Standard,Standard,Standard,Business,Business
Safety_and_Security,Standard,Standard,Standard,Premium,Standard,Standard,Standard,Standard,Premium,Standard,...,Premium,Premium,Business,Business,Premium,Business,Business,Business,Premium,Business
Extras,Standard,Standard,Standard,Business,Standard,Standard,Standard,Standard,Standard,Standard,...,Business,Premium,Standard,Standard,Business,Standard,Standard,Standard,Standard,Standard
Full_Service_History,0,0,0,1,0,0,0,0,0,0,...,1,1,0,0,1,0,0,1,1,1
Non_Smoker_Vehicle,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Emission_Class,6.0,6.0,6.0,4.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,4.0,5.0,6.0
Upholstery,0,0,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
Previous_Owner,1,1,1,2,1,1,1,1,1,1,...,1,1,1,1,1,2,1,2,1,1
Electric_Car,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Energy_Efficiency_Class,6,4,5,6,4,6,4,7,6,5,...,6,8,8,8,6,6,8,6,3,8
Taxi_or_Rental_Car,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Warranty_Category,3,2,2,2,2,3,2,2,2,2,...,2,2,2,2,2,2,2,2,3,2
First_Registration_Year,2016,2020,2015,2005,2018,2019,2019,2018,2015,2016,...,2019,2018,2018,2018,2018,2004,2019,2004,2011,2017
Age,6,2,7,17,4,3,3,4,7,6,...,3,4,4,4,4,18,3,18,11,5
General_Inspection_Year,2026,2026,2026,2026,2026,2026,2026,2026,2026,2026,...,2026,2024,2026,2026,2023,2023,2026,2023,2023,2026
Type_Demonstration,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Type_Employee's car,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Type_Pre-registered,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Type_Used,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
GB_Automatic,0,1,1,0,0,1,1,1,0,1,...,1,1,1,1,0,0,1,1,0,1
GB_Manual,1,0,0,1,1,0,0,0,1,0,...,0,0,0,0,1,1,0,0,1,0
GB_Semi-automatic,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FT_Benzine,0,1,0,1,0,1,1,0,0,1,...,1,1,0,0,0,1,0,1,0,1
FT_Bi-fuel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FT_Diesel,1,0,1,0,1,0,0,1,1,0,...,0,0,1,1,1,0,1,0,1,0
FT_Electric,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FT_LPG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FT_Other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df12=pd.get_dummies(df, prefix=['Location','Colour','Com_Con','EM','Saf_Sec','Extras'], columns=['Location','Colour','Comfort_and_Convenience','Entertainment_and_Media','Safety_and_Security','Extras'])
df12

,Make_Model,Make,Model,Price,Body_Type,Type,Doors,Mileage,Gearbox,Fuel_Type,...,Com_Con_Standard,EM_Business,EM_Premium,EM_Standard,Saf_Sec_Business,Saf_Sec_Premium,Saf_Sec_Standard,Extras_Business,Extras_Premium,Extras_Standard
0,Mercedes-Benz A 160,Mercedes-Benz,A 160,16950.0,Compact,Used,5,120200,Manual,Diesel,...,1,0,0,1,0,0,1,0,0,1
1,Mercedes-Benz A 35 AMG,Mercedes-Benz,A 35 AMG,46990.0,Compact,Used,5,18995,Automatic,Benzine,...,1,0,0,1,0,0,1,0,0,1
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,A 45 AMG,16800.0,Compact,Used,5,197000,Automatic,Diesel,...,0,0,0,1,0,0,1,0,0,1
3,Mercedes-Benz C 160,Mercedes-Benz,C 160,4690.0,Compact,Used,3,165000,Manual,Benzine,...,0,0,0,1,0,1,0,1,0,0
4,Mercedes-Benz CLA 180,Mercedes-Benz,CLA 180,22550.0,Compact,Used,5,83339,Manual,Diesel,...,1,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24124,Volvo S60,Volvo,S60,4999.0,Sedan,Used,4,166512,Manual,Benzine,...,0,0,0,1,1,0,0,0,0,1
24125,Volvo S90,Volvo,S90,37600.0,Sedan,Used,4,40345,Automatic,Diesel,...,0,0,0,1,1,0,0,0,0,1
24126,Volvo S40,Volvo,S40,5499.0,Sedan,Used,4,145000,Automatic,Benzine,...,0,0,0,1,1,0,0,0,0,1
24127,Volvo C30,Volvo,C30,7300.0,Sedan,Used,3,96000,Manual,Diesel,...,0,1,0,0,0,1,0,0,0,1
24128,Volvo S90,Volvo,S90,29900.0,Sedan,Used,4,94343,Automatic,Benzine,...,0,1,0,0,1,0,0,0,0,1

In [10]:
df_dummied=df12.copy()

In [11]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)